language: python

python:
  - '3.6'
  - '3.7'

cache: pip

install:
  - pip install codecov
  - pip install coverage
  - pip install -r requirements.txt
  - pip install -e .

script: coverage run --source scikit_posthocs setup.py test

after_success:
  - codecov
